server:
  port: 9903

  
spring:
  redis:
    host: 192.168.83.100
    port: 6379
    database: 0
    password: wangqiubao
    lettuce:
      pool:
        max-active: 32
        max-wait: 300
        max-idle: 16
        min-idle: 8
  local-redis:
    host: 192.168.83.100
    port: 6380
    database: 0
    password: wangqiubao
    lettuce:
      pool:
        max-active: 16
        max-wait: 100
        max-idle: 8
        min-idle: 4