server:
  port: 9903

  
spring:
  redis:
    host: redis-node
    port: 6381
    database: 14
    password: ucare@test!123
    lettuce:
      pool:
        max-active: 32
        max-wait: 300
        max-idle: 16
        min-idle: 8
  redis-two:
    host: redis-node
    port: 6381
    database: 15
    password: ucare@test!123
    lettuce:
      pool:
        max-active: 16
        max-wait: 100
        max-idle: 8
        min-idle: 4
  redis-three:
    host: redis-node
    port: 6381
    database: 13
    password: ucare@test!123
    lettuce:
      pool:
        max-active: 16
        max-wait: 100
        max-idle: 8
        min-idle: 4